networks:
  dev:
    driver: bridge

services:
  payload:
    container_name: centria-hub-front
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: centria-hub-db
    networks:
      - dev
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    logging:
      driver: none

volumes:
  data: