networks:
  dev:
    driver: bridge

services:
  client:
    container_name: centria-hub-front
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env